--- 
engines: 
  duplication: 
    config: 
      languages: 
        javascript: 
          mass_threshold: 55
    enabled: true
  eslint: 
    enabled: true
  fixme: 
    enabled: true
exclude_paths: 
  - test/
ratings: 
  paths: 
    - "**.inc"
    - "**.js"
    - "**.jsx"
    - "**.module"
    - "**.php"
    - "**.py"
    - "**.rb"
