language: node_js
node_js:
  - "stable"

script: npm run cover

addons:
  code_climate:
    repo_token: 056cdb26d8e4844f58cbff043a1953de51ebfe087c3840e0ec271d22e99ce12d

after_script:
  - ./node_modules/.bin/codeclimate-test-reporter < ./coverage/lcov.info